name: Running Test

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
      
    - name: setting envs in vm
      run: echo "${{secrets.ENVS_FILE }}" > .env
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Test the code
      run: |
        pip install python-dotenv
        python localTest.py

    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v5
      with:
        base: dev
        token: ${{ secrets.PAT }}
        commit-message: Update report
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: master
        delete-branch: false
        title: 'New Update'
        body: |
          Updated Code
          - Auto-generated by [create-pull-request][1]

        labels: |
          tested
          automated pr
        milestone: 1
        draft: false
